#!/usr/bin/env bash

# Run from this directory
cd "$(dirname -- "$(readlink -f -- "$0")")" || exit 1

# Secure to OpenFAOM.org
if [[ -f "$FOAM_ETC/controlDict" ]]; then
  echo " -> Hiding controlDict in $FOAM_ETC to work with OpenFOAM.org"
  mv $FOAM_ETC/controlDict $FOAM_ETC/controlDict.bak
fi

# Source tutorial run functions
source "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# ******************************************************************************


# Set start/end time and solver type for steady state simulation
startTime="${1:-0}"
endTime="${2:-2000}"
solver="${3:-simple}" # simple/simplec or pimple

echo "Foam simulation set up:"
case "$solver" in
    "simple")
        echo " ->     solver: SIMPLE!"
        ;;
    "simplec")
        echo " ->     solver: SIMPLE-C!"
        ;;
    "pimple")
        echo " ->     solver: PIMPLE!"
        ;;
    *)
        echo "Invalid solver! Abort ..."
        exit 1
        ;;
esac
echo " -> start time: $startTime"	
echo " ->   end time: $endTime"
echo


# -------------------------------
# --- Prepare the steady case ---
# -------------------------------
# Set steady state simulation control dict declarations
sed -i '/^#include.*/c\\#include "controlDict_ss"' system/controlDict
foamDictionary system/controlDict -entry startTime -set ${startTime}
foamDictionary system/controlDict -entry endTime -set ${endTime}

foamDictionary system/fvSchemes -entry ddtSchemes/default -set "steadyState"

# Choose between the SIMPLE/SIMPLEC or PIMPLE steady state solver
if [[ "$solver" == "simple" || "$solver" == "simplec" ]]; then
	if [[ "$solver" == "simple" ]]; then
		sed -i '/^#include.*/c\\#include "fvSolution.simple"' system/fvSolution
	else
		sed -i '/^#include.*/c\\#include "fvSolution.simplec"' system/fvSolution	
	fi
	
	sed -i '/^#include.*/c\\#include "fvSchemes.simple"' system/fvSchemes
	foamDictionary system/fvSchemes -entry ddtSchemes/default -set "steadyState"
else
	sed -i '/^#include.*/c\\#include "fvSchemes.pimple"' system/fvSchemes
	sed -i '/^#include.*/c\\#include "fvSolution.pimple"' system/fvSolution
	foamDictionary system/fvSchemes -entry ddtSchemes/default -set "steadyState"
fi


# Run in parallel steady state
mv log.foamRun log.foamRun_old
runParallel foamRun

# Reconstruct the latest result
runApplication reconstructPar -latestTime

# Do some post processing
foamPostProcess -latestTime -solver incompressibleFluid -func yPlus
foamPostProcess -latestTime -solver incompressibleFluid -func wallShearStress

# ******************************************************************************
